# Generated by Django 5.1.1 on 2024-09-22 15:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_habit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time_habit",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время выполнения привычки"
                    ),
                ),
                (
                    "action_habit",
                    models.CharField(max_length=100, verbose_name="Действие привычки"),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=True, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "number_of_executions_habit",
                    models.IntegerField(
                        default=1,
                        verbose_name="Количество выполнений привычки в неделю",
                    ),
                ),
                (
                    "duration_habit",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Продолжительность выполнения привычки",
                    ),
                ),
                (
                    "is_published_habit",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности привычки"
                    ),
                ),
                (
                    "reward_habit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение привычки",
                    ),
                ),
                (
                    "connection_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habits",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "creator_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
